export const usernameInput: string = '#identity'
export const passwordInput: string = '#password'
export const recoveryCodeInput: string = '#recovery_code'
export const loginSessionsFormSubmit: string = 'input[type=submit].loginSessionsForm_submit'
export const twoFactorAuthFormSubmit: string = 'form[action=/login/otp] input[type=submit]'
export const fileUploadButton: string = '.editorMarkdown_imagePicker input[type=file]'
export const markdownInputArea: string = 'textarea.editorMarkdown_textarea'
export const draftDeleteButton: string = '.draftsPreviewMenu_delete button'
